### PR TITLE
Fallback ListModels when offline

### LINKED ISSUE #124: ListModels request which includes includeRemote=true should not fail when offline
When looking into https://github.com/jelmervdl/translatelocally-web-ext/issues/62#issuecomment-1332349187 I noticed that TranslateLocally doesn't gracefully handle the offline scenario. That should be fixed.

### PR DESCRIPTION
**Pull request by jelmervdl**
When a ListModels request is handled with `includeRemote=True` but we're offline (or fetching fails for some reason) gracefully just return the local list of models.

I considered passing the error onto the caller, but the ListModels request can still partially succeed and serve its purpose. So falling back gracefully was the route I chose.

Fixes #124.

### CODE REVIEW

File: src/cli/NativeMsgIface.cpp [hunk 1]
```diff
@@ -204,13 +204,22 @@ void NativeMsgIface::handleRequest(TranslationRequest request) {
...
+        });
+
         // Note: this might pick up the completion of an earlier fetchRemoteModels()
         // request but that's okay since fetchRemoteModels() returns early if a
         // fetch is still in progress. Also, fetchedRemoteModels() is called
         // regardless of whether errors occurred during the fetching.
-        connectSingleShot(&models_, &ModelManager::fetchedRemoteModels, this, [this, request]([[maybe_unused]] QVariant ignored) {
-            handleRequest(request);
+        connectSingleShot(&models_, &ModelManager::fetchedRemoteModels, this, [this, requestCopy, errorConnection]([[maybe_unused]] QVariant ignored) {
+            QObject::disconnect(errorConnection);
```
Comment (XapaJIaMnu) [inline src/cli/NativeMsgIface.cpp:219]: Why do we need a disconnect here? Isn't errorConnection single shot?

Comment (jelmervdl) [reply src/cli/NativeMsgIface.cpp:219]: Yep, but if fetchedRemoteModels triggers without any errors, it will still be there once fetchedRemoteModels finished.

Maybe it would have been better if fetchedRemoteModels triggers in all cases, but when an error occurs it triggers with different arguments. That would remove this problem of catching either signal.

File: src/cli/NativeMsgIface.cpp [hunk 2]
```diff
@@ -204,13 +204,22 @@ void NativeMsgIface::handleRequest(TranslationRequest request) {
 void NativeMsgIface::handleRequest(ListRequest request)  {
     // Fetch remote models if necessary.
     if (request.includeRemote && models_.getRemoteModels().isEmpty()) {
+        std::shared_ptr<ListRequest> requestCopy(std::make_shared<ListRequest>(request));
```
Comment (XapaJIaMnu) [inline src/cli/NativeMsgIface.cpp:207]: Why are we not working on the requests directly?

Comment (jelmervdl) [reply src/cli/NativeMsgIface.cpp:207]: The function will have finished and `request` has gone out of scope by the time one of the callbacks is called. I copied it over to a shared_ptr so it can share a single request between the two signal handlers. Previously we just copied (or moved) the request into the one signal handler.
